[package]
name = "middle_square_method"
version = "0.1.0"
authors = ["Maciej Karpiński <karpfly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
